spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: root
    password: root
    schema: 'classpath:sanmu_schema.sql'
    data: 'classpath:sanmu_data.sql'
server.port: 8080
logging.level.root: debug