spring:
  datasource:
    url: jdbc:mysql://localhost:3306/huanggang?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
server.port: 8080
logging.level.root: info